#!/usr/bin/env bash
# Installs Nginx with the following configurations:
# Listens on port 80.
# Returns page containing "Hello World" when queried

apt-get update
apt-get install -y nginx

mkdir /var/www/nginx/html
touch /var/www/nginx/html/index.html
echo "Hello World" > /var/www/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/nginx/html;
     index       index.html;
}
" > /var/www/nginx/sites-available/default

service nginx restart
