#!/usr/bin/env bash
# Install nginx on your web-01 server
mkdir -p /var/www/html
chown -R $USER:$USER /var/www/html
chmod -R 755 /var/www
apt-get update
apt-get install -y nginx
chown -R ubuntu /var/www
echo "Hello World" > /var/www/html/index.nginx-debian.html
service nginx start
