#!/usr/bin/env bash
# Install your load balancer

sudo apt-get update
sudo apt -y install haproxy
echo "frontend Local_Server
    bind 10.10.255.92:80
    mode http
    default_backend My_Web_Servers
backend My_Web_Servers
    mode http
    balance roundrobin
    server web1 3.80.195.192:80 check
    server web2 107.21.190.38:80 check" >> /etc/haproxy/haproxy.cfg
systemctl restart haproxy
